require('./bootstrap');
// require('./vendor/modernizr-3.5.0.min');
// require('./vendor/jquery-2.2.4.min');
// require('./vendor/popper.min');
// require('./vendor/bootstrap.min');
// require('./owl.carousel.min');
// require('./metisMenu.min');
// require('./jquery.nice-select');
// require('./wow.min');
// require('./jquery.counterup.min');
// require('./waypoints.min');
// require('./jquery.scrollUp.min');
// require('./isotope.pkgd.min');
// require('./imagesloaded.pkgd.min');
// require('./jquery.magnific-popup.min');
// require('./plugins');
// require('./main');